services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    depends_on:
      celery_worker:
        condition: service_started
      migrate:
         condition: service_completed_successfully
      minio:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "-H", "x-api-key: ${X_API_KEY}", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: worker
    depends_on:
      redis:
        condition: service_healthy
      migrate:
         condition: service_completed_successfully
    command: uv run celery -A eden_summary.worker.worker worker
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  db:
    image: postgres:18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  migrate:
    build: .
    command: uv run alembic upgrade head
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  minio:
    image: quay.io/minio/aistor/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/mnt/data
      - ./minio/minio.license:/minio.license
    command: minio server /mnt/data --license /minio.license
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped